name = "Sophie"
author = "Cian"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3f99e427db1f5cfefd833fe7976c1d27c9122b2a006176426e00957ecf8ed21c"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
